version: "3.10"

services:
  web:
    container_name: fast_api_mysql
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c './wait-for-it.sh --timeout=0 db:3306 && uvicorn app.main:app --reload --host 0.0.0.0 --port 8080'
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@db:3306/practice
    depends_on:
      - db
  db:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: practice
      MYSQL_ROOT_PASSWORD: root

volumes:
    mysql:
    mysql_config: